import type { CatalogGraph } from "../../types";

// Native graph: design.md B06/B07, at the design's proposed layout.
// Illustrative presentation data, not a runnable n8n export.
export const GRAPH: CatalogGraph = {
  entryId: "blog-post-approval-and-scheduling",
  nodes: [
    {
      id: "M01",
      label: "Check content calendar",
      type: "n8n-nodes-base.scheduleTrigger",
      version: 1.4,
      x: 64,
      y: 96,
    },
    {
      id: "M02",
      label: "Get blog posts ready for review",
      type: "n8n-nodes-base.airtable",
      version: 2.2,
      x: 272,
      y: 96,
      alternatives: ["n8n-nodes-base.googleSheets"],
      display: { category: "Content calendar", tools: ["Airtable", "Google Sheets"] },
    },
    {
      id: "M03",
      label: "Get blog post draft",
      type: "n8n-nodes-base.googleDocs",
      version: 2,
      x: 480,
      y: 96,
      display: { category: "Documents" },
    },
    {
      id: "M04",
      label: "Save blog post review request",
      type: "n8n-nodes-base.postgres",
      version: 2.6,
      x: 688,
      y: 96,
      display: { category: "SQL database" },
    },
    {
      id: "M05",
      label: "New blog post version to review?",
      type: "n8n-nodes-base.if",
      version: 2.2,
      x: 896,
      y: 96,
    },
    {
      id: "M06",
      label: "Ask reviewer to approve blog post",
      type: "n8n-nodes-base.slack",
      version: 2.7,
      x: 1104,
      y: 96,
      alternatives: ["n8n-nodes-base.microsoftTeams"],
      display: { category: "Team chat", tools: ["Slack", "Microsoft Teams"] },
    },
    {
      id: "M07",
      label: "Reviewer approved blog post?",
      type: "n8n-nodes-base.if",
      version: 2.2,
      x: 1312,
      y: 96,
    },
    {
      id: "M08",
      label: "Get blog post draft again",
      type: "n8n-nodes-base.googleDocs",
      version: 2,
      x: 64,
      y: 400,
      display: { category: "Documents" },
    },
    {
      id: "M09",
      label: "Record blog post approval",
      type: "n8n-nodes-base.postgres",
      version: 2.6,
      x: 272,
      y: 400,
      display: { category: "SQL database" },
    },
    {
      id: "M10",
      label: "Approved blog post still current?",
      type: "n8n-nodes-base.if",
      version: 2.2,
      x: 480,
      y: 400,
    },
    {
      id: "M11",
      label: "Format blog post for website",
      type: "n8n-nodes-base.code",
      version: 2,
      x: 688,
      y: 400,
    },
    {
      id: "M12",
      label: "Schedule blog post",
      type: "n8n-nodes-base.wordpress",
      version: 1,
      x: 896,
      y: 400,
      alternatives: ["n8n-nodes-base.ghost"],
      display: { category: "Website CMS", tools: ["WordPress", "Ghost"] },
    },
    {
      id: "M13",
      label: "Save scheduled blog post link",
      type: "n8n-nodes-base.postgres",
      version: 2.6,
      x: 1104,
      y: 400,
      display: { category: "SQL database" },
    },
    {
      id: "M14",
      label: "Mark blog post scheduled",
      type: "n8n-nodes-base.airtable",
      version: 2.2,
      x: 1312,
      y: 400,
      alternatives: ["n8n-nodes-base.googleSheets"],
      display: { category: "Content calendar", tools: ["Airtable", "Google Sheets"] },
    },
    {
      id: "M15",
      label: "Record blog post not approved",
      type: "n8n-nodes-base.postgres",
      version: 2.6,
      x: 272,
      y: 608,
      display: { category: "SQL database" },
    },
    {
      id: "M16",
      label: "Return blog post to writer",
      type: "n8n-nodes-base.airtable",
      version: 2.2,
      x: 480,
      y: 608,
      alternatives: ["n8n-nodes-base.googleSheets"],
      display: { category: "Content calendar", tools: ["Airtable", "Google Sheets"] },
    },
  ],
  edges: [
    {
      id: "E01",
      kind: "main",
      from: { node: "M01", index: 0 },
      to: { node: "M02", index: 0 },
      path: "M160 144 H272",
    },
    {
      id: "E02",
      kind: "main",
      from: { node: "M02", index: 0 },
      to: { node: "M03", index: 0 },
      path: "M368 144 H480",
    },
    {
      id: "E03",
      kind: "main",
      from: { node: "M03", index: 0 },
      to: { node: "M04", index: 0 },
      path: "M576 144 H688",
    },
    {
      id: "E04",
      kind: "main",
      from: { node: "M04", index: 0 },
      to: { node: "M05", index: 0 },
      path: "M784 144 H896",
    },
    {
      id: "E05",
      kind: "main",
      from: { node: "M05", index: 0 },
      to: { node: "M06", index: 0 },
      path: "M992 128 H1060 Q1076 128 1076 144 H1104",
    },
    {
      id: "E06",
      kind: "main",
      from: { node: "M06", index: 0 },
      to: { node: "M07", index: 0 },
      path: "M1200 144 H1312",
    },
    // The approved branch returns along the right edge and the row gap to the second row.
    {
      id: "E07",
      kind: "main",
      from: { node: "M07", index: 0 },
      to: { node: "M08", index: 0 },
      path: "M1408 128 H1456 Q1472 128 1472 144 V304 Q1472 320 1456 320 H48 Q32 320 32 336 V432 Q32 448 48 448 H64",
    },
    {
      id: "E08",
      kind: "main",
      from: { node: "M08", index: 0 },
      to: { node: "M09", index: 0 },
      path: "M160 448 H272",
    },
    {
      id: "E09",
      kind: "main",
      from: { node: "M09", index: 0 },
      to: { node: "M10", index: 0 },
      path: "M368 448 H480",
    },
    {
      id: "E10",
      kind: "main",
      from: { node: "M10", index: 0 },
      to: { node: "M11", index: 0 },
      path: "M576 432 H644 Q660 432 660 448 H688",
    },
    {
      id: "E11",
      kind: "main",
      from: { node: "M11", index: 0 },
      to: { node: "M12", index: 0 },
      path: "M784 448 H896",
    },
    {
      id: "E12",
      kind: "main",
      from: { node: "M12", index: 0 },
      to: { node: "M13", index: 0 },
      path: "M992 448 H1104",
    },
    {
      id: "E13",
      kind: "main",
      from: { node: "M13", index: 0 },
      to: { node: "M14", index: 0 },
      path: "M1200 448 H1312",
    },
    // The not-approved branch runs below the second row and enters the third row from the left.
    {
      id: "E14",
      kind: "main",
      from: { node: "M07", index: 1 },
      to: { node: "M15", index: 0 },
      path: "M1408 160 H1488 Q1504 160 1504 176 V816 Q1504 832 1488 832 H48 Q32 832 32 816 V672 Q32 656 48 656 H272",
    },
    {
      id: "E15",
      kind: "main",
      from: { node: "M15", index: 0 },
      to: { node: "M16", index: 0 },
      path: "M368 656 H480",
    },
  ],
  annotations: [
    { id: "N1", text: "No new review request", at: { node: "M05", index: 1 } },
    { id: "N2", text: "Blog post scheduled", at: { node: "M14", index: 0 } },
    { id: "N3", text: "Blog post not scheduled", at: { node: "M10", index: 1 } },
    { id: "N4", text: "Blog post not approved", at: { node: "M16", index: 0 } },
  ],
  phases: [
    { id: "P1", nodes: ["M01", "M02", "M03"] },
    { id: "P2", nodes: ["M04", "M05", "M06", "M07", "M15", "M16"] },
    { id: "P3", nodes: ["M08", "M09", "M10"] },
    { id: "P4", nodes: ["M11", "M12", "M13", "M14"] },
  ],
  presentation: {
    kind: "flow",
    openingMs: 900,
    beats: [
      { durationMs: 1500, phases: ["P1"], nodes: ["M01", "M02", "M03"], edges: ["E01", "E02"] },
      {
        durationMs: 1900,
        phases: ["P2"],
        nodes: ["M04", "M05", "M06", "M07"],
        edges: ["E03", "E04", "E05", "E06"],
      },
      {
        durationMs: 1500,
        phases: ["P3"],
        nodes: ["M08", "M09", "M10"],
        edges: ["E07", "E08", "E09"],
      },
      {
        durationMs: 1900,
        phases: ["P4"],
        nodes: ["M11", "M12", "M13", "M14"],
        edges: ["E10", "E11", "E12", "E13"],
      },
    ],
    ending: "N2",
  },
};
