/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsAiBookingAgentRouteImport } from './routes/projects/ai-booking-agent'
import { Route as ProjectsLeadRoutingPipelineHealthSystemRouteImport } from './routes/projects/lead-routing-pipeline-health-system'
import { Route as ProjectsTrialDemoRoutingByCustomerRelationshipRouteImport } from './routes/projects/trial-demo-routing-by-customer-relationship'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAiBookingAgentRoute = ProjectsAiBookingAgentRouteImport.update({
  id: '/projects/ai-booking-agent',
  path: '/projects/ai-booking-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsLeadRoutingPipelineHealthSystemRoute =
  ProjectsLeadRoutingPipelineHealthSystemRouteImport.update({
    id: '/projects/lead-routing-pipeline-health-system',
    path: '/projects/lead-routing-pipeline-health-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsTrialDemoRoutingByCustomerRelationshipRoute =
  ProjectsTrialDemoRoutingByCustomerRelationshipRouteImport.update({
    id: '/projects/trial-demo-routing-by-customer-relationship',
    path: '/projects/trial-demo-routing-by-customer-relationship',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/ai-booking-agent': typeof ProjectsAiBookingAgentRoute
  '/projects/lead-routing-pipeline-health-system': typeof ProjectsLeadRoutingPipelineHealthSystemRoute
  '/projects/trial-demo-routing-by-customer-relationship': typeof ProjectsTrialDemoRoutingByCustomerRelationshipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/ai-booking-agent': typeof ProjectsAiBookingAgentRoute
  '/projects/lead-routing-pipeline-health-system': typeof ProjectsLeadRoutingPipelineHealthSystemRoute
  '/projects/trial-demo-routing-by-customer-relationship': typeof ProjectsTrialDemoRoutingByCustomerRelationshipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/ai-booking-agent': typeof ProjectsAiBookingAgentRoute
  '/projects/lead-routing-pipeline-health-system': typeof ProjectsLeadRoutingPipelineHealthSystemRoute
  '/projects/trial-demo-routing-by-customer-relationship': typeof ProjectsTrialDemoRoutingByCustomerRelationshipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/ai-booking-agent'
    | '/projects/lead-routing-pipeline-health-system'
    | '/projects/trial-demo-routing-by-customer-relationship'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/ai-booking-agent'
    | '/projects/lead-routing-pipeline-health-system'
    | '/projects/trial-demo-routing-by-customer-relationship'
  id:
    | '__root__'
    | '/'
    | '/projects/ai-booking-agent'
    | '/projects/lead-routing-pipeline-health-system'
    | '/projects/trial-demo-routing-by-customer-relationship'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsAiBookingAgentRoute: typeof ProjectsAiBookingAgentRoute
  ProjectsLeadRoutingPipelineHealthSystemRoute: typeof ProjectsLeadRoutingPipelineHealthSystemRoute
  ProjectsTrialDemoRoutingByCustomerRelationshipRoute: typeof ProjectsTrialDemoRoutingByCustomerRelationshipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/ai-booking-agent': {
      id: '/projects/ai-booking-agent'
      path: '/projects/ai-booking-agent'
      fullPath: '/projects/ai-booking-agent'
      preLoaderRoute: typeof ProjectsAiBookingAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/lead-routing-pipeline-health-system': {
      id: '/projects/lead-routing-pipeline-health-system'
      path: '/projects/lead-routing-pipeline-health-system'
      fullPath: '/projects/lead-routing-pipeline-health-system'
      preLoaderRoute: typeof ProjectsLeadRoutingPipelineHealthSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/trial-demo-routing-by-customer-relationship': {
      id: '/projects/trial-demo-routing-by-customer-relationship'
      path: '/projects/trial-demo-routing-by-customer-relationship'
      fullPath: '/projects/trial-demo-routing-by-customer-relationship'
      preLoaderRoute: typeof ProjectsTrialDemoRoutingByCustomerRelationshipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsAiBookingAgentRoute: ProjectsAiBookingAgentRoute,
  ProjectsLeadRoutingPipelineHealthSystemRoute:
    ProjectsLeadRoutingPipelineHealthSystemRoute,
  ProjectsTrialDemoRoutingByCustomerRelationshipRoute:
    ProjectsTrialDemoRoutingByCustomerRelationshipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
