import type { CatalogGraph } from "../../types";

// Native graph: design.md B06/B07, connections revision 2026-10-04 (quotes and tasks in
// the CRM, the follow-up recorded first in the SQL database), at the design's proposed layout.
// Illustrative presentation data, not a runnable n8n export.
export const GRAPH: CatalogGraph = {
  entryId: "quote-follow-up-reminders",
  nodes: [
    {
      id: "R01",
      label: "Check quote follow-ups",
      type: "n8n-nodes-base.scheduleTrigger",
      version: 1.4,
      x: 80,
      y: 96,
    },
    {
      id: "R02",
      label: "Get quotes awaiting reply",
      type: "n8n-nodes-base.hubspot",
      version: 2.2,
      x: 288,
      y: 96,
      alternatives: ["n8n-nodes-base.salesforce", "n8n-nodes-base.highLevel"],
      display: { category: "CRM", tools: ["HubSpot", "Salesforce", "GHL"] },
    },
    {
      id: "R03",
      label: "Check quote and reply",
      type: "n8n-nodes-base.code",
      version: 2,
      x: 496,
      y: 96,
    },
    {
      id: "R04",
      label: "Ready to follow up?",
      type: "n8n-nodes-base.if",
      version: 2.2,
      x: 704,
      y: 96,
    },
    {
      id: "R05",
      label: "Save follow-up record",
      type: "n8n-nodes-base.postgres",
      version: 2.6,
      x: 912,
      y: 96,
      display: { category: "SQL database" },
    },
    {
      id: "R06",
      label: "New task needed?",
      type: "n8n-nodes-base.if",
      version: 2.2,
      x: 1120,
      y: 96,
    },
    {
      id: "R08",
      label: "Create follow-up task",
      type: "n8n-nodes-base.hubspot",
      version: 2.2,
      x: 1328,
      y: 96,
      alternatives: ["n8n-nodes-base.salesforce", "n8n-nodes-base.highLevel"],
      display: { category: "CRM", tools: ["HubSpot", "Salesforce", "GHL"] },
    },
    {
      id: "R09",
      label: "Save task link",
      type: "n8n-nodes-base.postgres",
      version: 2.6,
      x: 1328,
      y: 368,
      display: { category: "SQL database" },
    },
    {
      id: "R07",
      label: "Record the check",
      type: "n8n-nodes-base.postgres",
      version: 2.6,
      x: 912,
      y: 368,
      display: { category: "SQL database" },
    },
  ],
  edges: [
    {
      id: "E01",
      kind: "main",
      from: { node: "R01", index: 0 },
      to: { node: "R02", index: 0 },
      path: "M176 144 H288",
    },
    {
      id: "E02",
      kind: "main",
      from: { node: "R02", index: 0 },
      to: { node: "R03", index: 0 },
      path: "M384 144 H496",
    },
    {
      id: "E03",
      kind: "main",
      from: { node: "R03", index: 0 },
      to: { node: "R04", index: 0 },
      path: "M592 144 H704",
    },
    {
      id: "E04",
      kind: "main",
      from: { node: "R04", index: 0 },
      to: { node: "R05", index: 0 },
      path: "M800 128 H868 Q884 128 884 144 H912",
    },
    {
      id: "E05",
      kind: "main",
      from: { node: "R05", index: 0 },
      to: { node: "R06", index: 0 },
      path: "M1008 144 H1120",
    },
    {
      id: "E07",
      kind: "main",
      from: { node: "R06", index: 0 },
      to: { node: "R08", index: 0 },
      path: "M1216 128 H1284 Q1300 128 1300 144 H1328",
    },
    // The task link returns along the right edge, then turns into the row below.
    {
      id: "E08",
      kind: "main",
      from: { node: "R08", index: 0 },
      to: { node: "R09", index: 0 },
      path: "M1424 144 H1472 Q1488 144 1488 160 V288 Q1488 304 1472 304 H1296 Q1280 304 1280 320 V400 Q1280 416 1296 416 H1328",
    },
    // The false branch turns down before R05's body, so it never crosses the true branch.
    {
      id: "E06",
      kind: "main",
      from: { node: "R04", index: 1 },
      to: { node: "R07", index: 0 },
      path: "M800 160 H832 V416 H912",
    },
  ],
  annotations: [
    { id: "N1", text: "Follow-up ready", at: { node: "R09", index: 0 } },
    { id: "N2", text: "No new task", at: { node: "R06", index: 1 } },
    { id: "N3", text: "Check recorded", at: { node: "R07", index: 0 } },
  ],
  phases: [
    { id: "P1", nodes: ["R01", "R02"] },
    { id: "P2", nodes: ["R03", "R04", "R07"] },
    { id: "P3", nodes: ["R05", "R06"] },
    { id: "P4", nodes: ["R08", "R09"] },
  ],
  presentation: {
    kind: "flow",
    openingMs: 900,
    beats: [
      { durationMs: 1500, phases: ["P1"], nodes: ["R01", "R02"], edges: ["E01"] },
      { durationMs: 1850, phases: ["P2"], nodes: ["R03", "R04"], edges: ["E02", "E03"] },
      { durationMs: 1450, phases: ["P3"], nodes: ["R05", "R06"], edges: ["E04", "E05"] },
      { durationMs: 1600, phases: ["P4"], nodes: ["R08", "R09"], edges: ["E07", "E08"] },
    ],
    ending: "N1",
  },
};
